unjs/unstorage

- src/utils.ts
- test/storage.test.ts
`key` argument is optional in some functions, like (`getKeys`)
- Add default value for key argument to prevent undefined key (`base:undefined`)
- Normalize `base + key` to remove ending `:` in case of missing key (`base:`)
> fix(prefixStorage): handle missing key

- src/storage.ts
- src/types.ts
This PR allows drivers to filter out keys in `geyKeys` method.
If our driver was mounted on `/tmp/foo` and someone calls `getKeys('/tmp/foo/bar')`, the getkeys function of driver will receive `/bar` as its argument and it can filter out the result.
This will help up to improve speed/performance for some drivers like fsDriver
> feat: allow driver getKey to receive base key

- build.config.ts
`unstorage@0.3.0` exports `/drivers/*.cjs`, But with current unbuild config, driver files generates as `.js` files.
This changes enforce unbuild to use `.cjs` for drivers.
> fix(build): use cjs extension for drivers

- src/storage.ts
- test/storage.test.ts
Resolves #27
This PR includes two important fixes when a mount is shadowing parent (`/mnt` mounting on `/` when main mount has keys under `mnt:` namespace)
- Avoid returning parent keys with `getKeys`
- Avoid calling `clear` on the entire parent!
> fix: handle mount overrides

- README.md
- src/drivers/github.ts
Create Github driver using Github API and raw CDN
- Use API to fetch files
- Use Github raw CDN to fetch file content
- Cache files to 10 minutes (configurable by `ttl`)
- Accept `dir` to load contents from specific directory
> feat: `github` driver

- README.md
- package.json
- pnpm-lock.yaml
- src/drivers/cloudflare-kv-http.ts
- test/drivers/cloudflare-kv-http.test.ts
Add `cloudflare-kv-http` driver for Cloudflare KV using Cloudflare's REST API. Allows KV to be used outside of a CF worker environment.
Uses `msw` (https://mswjs.io/) to provide a mock server for tests.
closes #31
> feat: `cloudflare-kv-http` driver

- src/drivers/cloudflare-kv-binding.ts
Bugfix - Cloudflare KV Bindings driver
When using the Cloudflare KV Bindings driver `getKeys(base?: string)` method with a `base` argument, an error is thrown in production.
The Cloudflare KV `list` method requires an Object `{ prefix: <base>}` to filter by prefix. This PR creates this object if a `base` argument is provided to the driver's `getKeys()` method.
> fix(drivers): add prefix key for cloudflare kv list operation

- src/drivers/redis.ts
> fix(redis): fix reference in `clear()` method

- src/drivers/github.ts
This PR removes leading slashes from file tree prefixes and fixes the default config's functionality.
The Github REST API's tree paths don't contain leading slashes, so setting the `dir` option to `/docs` or leaving it as default (`''`) was causing the driver to view these trees as empty.
> fix(github): trim leading slash on `dir` prefix paths

- README.md
Should be `storageServer` instead of `storage`, as in https://github.com/unjs/unstorage/blob/main/demo/vite.config.ts#L23
> docs: fix `storageServer.handle` example

- build.config.ts
- package.json
this generates some declarations re-exporting the types from the real declarations in `dist`, for versions of typescript without subpath type support, so users get type support when doing something like:
```js
import fs from 'unstorage/drivers/fs'
```
instead of needing to do:
```ts
// @ts-expect-error
import _fs from 'unstorage/drivers/fs'
const fs = _fs as typeof import('unstorage/dist/drivers/fs')['default']
```
> build: provide backwards-compatible type entries

- src/drivers/cloudflare-kv-http.ts
Currently we spread the params within `ofetch` so we never actually end up passing any to the fetcher, meaning currently this (if the number of keys is high enough to warrant pagination) just requests the same list of keys over and over again until it times out.
> fix(cloudflare): pass params to kv request

- README.md
- src/_utils.ts
- src/drivers/fs.ts
- src/drivers/memory.ts
- src/drivers/utils/node-fs.ts
- src/storage.ts
- src/types.ts
- test/drivers/cloudflare-kv-http.test.ts
- test/drivers/fs.test.ts
- test/drivers/utils.ts
Resolves #21
Resolves #121
This PR supports the storing and retrieval of raw values using the new `getItemRaw`/`setItemRaw` interface.
Drivers can opt-in to implement `getItemRaw`/`setItemRaw` as well. When they do, unstorage directly uses this interface instead of getItem/setItem.
For drivers not supporting raw format, unstorage uses a compatibility layer to serialize and deserialize raw values with `base64:` protocol. Raw input can be any value supported by [`Buffer.from`(https://nodejs.org/api/buffer.html). This support is now added for `fs` (node) and `memory` (universal)
Followup https://github.com/unjs/unstorage/issues/142
> feat: raw data support (experimental)

- src/drivers/planetscale.ts
> fix(planetscale): use `birthtime` for `created_at` value

- src/_utils.ts
- test/storage.test.ts
With the new "stringify" implementation, trying to store an array throws an error. Here's a simple repro: https://stackblitz.com/edit/typescript-xvqbbc?file=index.ts
> fix: allow stringify array

- src/drivers/redis.ts
- test/drivers/utils.ts
> fix(redis): fix clear method

- docs/content/2.usage.md
- docs/content/5.custom-driver.md
- src/storage.ts
- src/types.ts
This PR allows passing an extendable options parameter to all transaction functions in storage and drivers.
This unlocks a way to support transactional authentication (single storage multi user) and native options such as ttl like https://github.com/unjs/unstorage/issues/35
> feat: allow passing transaction options to drivers

- docs/content/6.drivers/redis.md
- src/drivers/redis.ts
Resolves #35
Support setting ttl for all setItem operations or per setItem using new transaction options
> feat(redis): support native `ttl`

- docs/content/4.http-server.md
- src/drivers/http.ts
- src/server.ts
- test/drivers/http.test.ts
- test/server.test.ts
This PR brings several improvements to `http` driver and compliant HTTP server:
- Properly apply a base for `getKeys` operation
- Native raw support (`application/octet-stream`)
- Implemented clear method (DELETE with `:` or `/` ending path)
- Passing standard test suit over http
- Exposed new `createH3StorageHandler`
> feat: `http` and server improvements

- docs/content/4.http-server.md
- src/server.ts
- test/server.test.ts
Add `authorize` method in order to allow protecting server
> feat(server): support authorize

- .prettierignore
- docs/content/6.drivers/lru-cache.md
- src/drivers/lru-cache.ts
- test/drivers/lru-cache.test.ts
- test/drivers/utils.ts
Support `maxSize` and `maxEntrySize` for lru-cache driver with built-in size calculation setup
> feat(lru-cache): support `maxSize` and `maxEntrySize`

- package.json
resolves #182
pnpm seems to install all optional dependencies.
Using `peerDependencies` + `optional` meta to fix this.
> fix(pkg): use optional peer dependencies

- docs/content/6.drivers/session-storage.md
- src/drivers/session-storage.ts
- src/index.ts
- test/drivers/session-storage.test.ts
Hi !
This PR adds the [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) driver
> feat(drivers): add session storage driver

- README.md
- docs/content/1.index.md
This is a straightforward typo fix.
Followed the instructions in `docs/README.md` and checked that the fix worked.
> docs: fix typo

- src/drivers/github.ts
The supposedly optional driver properties aren't optional on the interface, which makes configuration more work than it needs to be.
This PR makes `branch`, `dir` and `ttl` optional, as they have defaults.
> fix(github): optional properties

- src/drivers/cloudflare-kv-binding.ts
Context: https://github.com/unjs/nitro/issues/1132 and https://github.com/unjs/nitro/pull/1147
By lazy accessing binding, we can update it later after initialization of driver instance inside handlers.
> fix(cloudflare): allow lazy access to env bindings

- docs/content/6.drivers/cloudflare-kv-http.md
Update cloudflare-kv-http.md. 
Change `environemnt` to `environment`
> docs: fix typo in drivers/cloudflare-kv-http

- test/drivers/github.test.ts
resolves https://github.com/unjs/unstorage/issues/258
This PR adds tests to the github driver against the unstorage repo.
> test: add test for `github` driver

- docs/content/6.drivers/memory.md
The implementation uses Map rather than Set. 
Aligned docs to implementation.
See https://github.com/unjs/unstorage/blob/main/src/drivers/memory.ts#L6
> docs: fix memory driver description

- docs/content/6.drivers/planetscale.md
- docs/package.json
- docs/pnpm-lock.yaml
Should resolves #309 
Let's wait for preview
> docs: update deps

- docs/content/6.drivers/azure-key-vault.md
- src/drivers/azure-key-vault.ts
- Updated key encoding/decoding to avoid decoding errors
- Updated docs with additional usage hints
> fix(azure-key-vault-driver): fix character encoding

- src/drivers/lru-cache.ts
- src/drivers/memory.ts
- src/drivers/mongodb.ts
- src/drivers/redis.ts
- test/drivers/cloudflare-kv-binding.test.ts
- test/drivers/cloudflare-kv-http.test.ts
- test/drivers/cloudflare-r2-binding.test.ts
- test/drivers/redis.test.ts
- test/drivers/utils.ts
- no related issue, just created fix when discovered it
I have noticed, that values resolved as Falsy were returned as `null`.
This PR is adding test for the driver to check if it returns values like `0` or `false` and not `null` and replaced some of the drivers that were returning incorrect results.
As the result `null` is returned only when:
1. there is no value in storage
2. value in storage is `null`
3. value in storage is `undefined`
cheers :)
> fix(lru-cache, memory, mongodb, redis): return falsy values when set in storage

- docs/2.drivers/redis.md
- package.json
- pnpm-lock.yaml
Currently ioredis will be installed, even if you are not using it. With this change ioredis will be an optional peerDependency and you have to manually install it. 
Resolves: #409
> fix(pkg): make `ioredis` dependency optional

- src/storage.ts
- test/storage.test.ts
https://github.com/unjs/unstorage/pull/390#discussion_r1471070500
The setItems function first calls the setItems, and the setItem for each element.
This is the test result before the change:
and this is after:
> fix(setItems): call driver native `setItems` only to avoid duplicate write

- src/types.ts
The type isn't using the generic so the types are broken when augmenting with a generic.
For consistency with `getItem` we also allow augmenting at a function level `getItems<{ foo: 'bar' }>`.
Also seems like the `value` was only accepting `string` for `setItems` whcih I've included a fix for also.
> fix: `getItems`, `setItems` types

- docs/2.drivers/azure.md
- docs/2.drivers/browser.md
- docs/2.drivers/capacitor-preferences.md
- docs/2.drivers/mongodb.md
- docs/2.drivers/redis.md
I noticed documentations for drivers were showing only the `npm i` command.
I changed them to use the package manager component from undocs.
> docs: using undocs package manager component

- src/drivers/cloudflare-kv-binding.ts
This will give the prefix and avoid looping through all the main namespace, this is an important fix in term of performance when dealing with a lot of keys.
> perf(cloudflare-kv-binding): add missing base argument on `getKeys`

- docs/2.drivers/http.md
- src/drivers/http.ts
- src/server.ts
- src/types.ts
- test/server.test.ts
Some drivers (cloudflare, vercel, and Redis) support the native `ttl` transaction option.
With HTTP/server pair to do remote operations, these parameters weren't passing.
This PR supports it by using the custom `x-ttl` HTTP header in requests for `setItem` and `x-ttl` + `Cache-Control: max-age=<ttl>` response headers for server HEAD/GET responses.
**Note:** This feature is not to pass arbitrary transaction options (as they can contain sensitive information or large payload) and also not arbitrary support of `ttl` as (stored) meta but only for the drivers that support it natively. in later versions we support arbitrary value+meta as FormData body.
> feat(http, server): support native `ttl`

- src/drivers/cloudflare-kv-binding.ts
- src/drivers/cloudflare-kv-http.ts
(credits to @atinux for noticing this)
According to [cloudflare docs](https://developers.cloudflare.com/kv/api/write-key-value-pairs/), the minimum amount of `ttl` is 60 seconds. This PR adds a fix to make sure if ttl is set, it is a minimum of 60 seconds (configurable via `minTTL` if needed) instead of throwing error in production.
> fix(cloudflare-kv): use min ttl of 60 seconds

- package.json
- pnpm-lock.yaml
- src/drivers/fs.ts
- https://github.com/nuxt/nuxt/issues/29744
- https://github.com/vitejs/vite/issues/18527
Revert Chokidar to v3 temporarily (updated in v1.13.0 via #489) due to downstream issues.
> fix: revert chokidar to v3

- docs/2.drivers/cloudflare.md
- src/drivers/cloudflare-r2-binding.ts
- test/drivers/cloudflare-r2-binding.test.ts
(context: #517 by @MickL)
This PR allows `getItemRaw(key, { type: "..." })` with specified return type based on user needs: object/stream/blob/bytes/arrayBuffer are possible (check docs)
> feat(cloudflare-r2-binding): allow specify raw type

- docs/2.drivers/deno.md
- package.json
- pnpm-lock.yaml
- src/drivers/deno-kv-node.ts
- src/drivers/deno-kv.ts
- src/index.ts
- test/drivers/deno-kv-node.test.ts
Followup PR for #233, this adds Deno KV support for Node.js via `@deno/kv` (rework of #391)
Most of logic is reused, a new `openKv` is exposed from base `deno-kv` driver to allow wrapping it with package. (users can provide their own `openKv` as well)
> feat: `deno-kv-node` driver

- docs/2.drivers/netlify.md
Updates the Netlify driver docs to add the `consistency` option, and the advanced option `uncachedEdgeURL`.
> docs(netlify): add consistency option

- .github/workflows/autofix.yml
- .prettierignore
- build.config.ts
- package.json
- pnpm-lock.yaml
- scripts/gen-drivers.ts
- src/_drivers.ts
- src/index.ts
- tsconfig.json
Auto-generate meta data for `builtinDrivers`, `BuiltinDriverName` and `BuiltinDriverOptions` exports.
This PR adds consistent kebab-case + camelCase variants to all exports.
Another change by this PR is that we don't double bundle driver options types anymore and types are reused from `unstorage/drivers/` making dist size almost half!
<details>
```ts
// Auto-generated using scripts/gen-drivers.
// Do not manually edit!
import type { AzureAppConfigurationOptions as AzureAppConfigurationOptions } from "unstorage/drivers/azure-app-configuration";
import type { AzureCosmosOptions as AzureCosmosOptions } from "unstorage/drivers/azure-cosmos";
import type { AzureKeyVaultOptions as AzureKeyVaultOptions } from "unstorage/drivers/azure-key-vault";
import type { AzureStorageBlobOptions as …
```
> build: generate drivers meta

- src/drivers/http.ts
(credits to @itpropro for dicovery in #364)
`getItemRaw` for `http` driver was using ofetch default (text string). This PR fixes to use `arrayBuffer` (consistent with most of other drivers raw value)
> fix(http): return `arrayBuffer` for `getItemRaw`

- src/drivers/localstorage.ts
- test/drivers/localstorage.test.ts
resolves #352
(fix added to localstorage only since merging it to webstorge in #338)
> fix(localstorage): consider `base` for `clear` and `getKeys`

- docs/2.drivers/browser.md
- src/drivers/localstorage.ts
- src/drivers/session-storage.ts
resolves #203 (rework of #338 -- by @thecotne ❤️)
session-storage logic is almost identical to localstorage driver. this PR reuses same logic of localstorage and adds generic options.
> refactor: reuse `localstorage` logic for `session-storage`

- src/storage.ts
- src/types.ts
- src/utils.ts
- test/storage.test-d.ts
resolves https://github.com/unjs/unstorage/issues/531
we didn't catch the issue because `toMatchTypeOf` doesn't mean what it sounds like
> fix(types): fallback to `StorageValue` for un-typed stores

- src/drivers/db0.ts
- test/drivers/db0.test.ts
resolves #537
mysql column names need escaping with backtracks 
(note: tests ran locally)
> fix(db): escape mysql queries

- src/drivers/s3.ts
- src/drivers/utils/index.ts
- test/drivers/s3.test.ts
resolves #544
s3 urls should use `/` as sep for external compatibility.
> fix(s3): use `/` as separator

- test/drivers/cloudflare-kv-binding.test.ts
- test/drivers/cloudflare-r2-binding.test.ts
- test/drivers/fs-lite.test.ts
- test/drivers/fs.test.ts
- test/drivers/localstorage.test.ts
- test/drivers/redis.test.ts
- test/drivers/session-storage.test.ts
- test/drivers/utils.ts
Clears the storage after each test such that they no longer rely on run order, etc.
Note that the two snapshot tests have been massively dumbed down. Though I'm not sure this is a problem since the underlying driver tests already test the data types etc. Leaving these to purely test that _a_ snapshot can be produced. 
let me know what you think
> test: clear storage after each test

- src/utils.ts
- test/storage.test.ts
When creating a prefixed storage, the `get`, `set`, `has`, `del`, `remove` aliases don't work as intended (they do not get the defined prefixe) as they are not defined in the `storageKeyProperties` in https://github.com/unjs/unstorage/blob/main/src/utils.ts
- Added `get`, `set`, `has`, `del`, `remove` in `storageKeyProperties`
- Added regression tests 
Related with breaking changes : https://github.com/unjs/unstorage/pull/455
> fix(prefixStorage): wrap shorthand aliases

- src/types.ts
resolves #549
Adds `flags` to the `Driver` type which can be used in future to determine if a driver supports a particular feature or requires some behaviour.
maybe something like this @pi0 ? and in a separate PR, add the flags to the fs drivers
> feat: add `flags` key to driver interface

- vite.config.mjs
The compiled `drivers` directory was being considered for test coverage. This change excludes that directory along with the `scripts` directory to have a more accurate coverage report.
**Before**
**After**
> test: exclude drivers and scripts directories from test coverage

- src/drivers/fs-lite.ts
- src/drivers/fs.ts
- src/drivers/utils/node-fs.ts
- test/drivers/fs-lite.test.ts
- test/drivers/fs.test.ts
Adds native support for `maxDepth` to the `fs` and `fs-lite` drivers.
This works by traversing directories only until the depth has been met.
> feat(fs, fs-lite): native `maxDepth` support

- src/drivers/fs-lite.ts
- src/drivers/fs.ts
- src/storage.ts
- test/storage.test.ts
Skips `maxDepth` filtering if _all_ drivers in the current storage instance natively support it (via the `maxDepth` flag).
Also enables the `maxDepth` flag for `fs` and `fs-lite` drivers.
Depends on #551
> perf: skip `maxDepth` filtering if natively supported

- package.json
- pnpm-lock.yaml
- src/drivers/fs.ts
We initially upgraded to chokidar v4 (#489) then reverted back to #502 as a hotfix (see relevant issues)
Stability and ecosystem adoption seem now much better. The only remaining part is that chokidar v4 dropped glob support. 
This PR updates to use same `anymatch` matcher we use for listing key filtering, to also apply to `watchOptions.ignored`
- ~~If users already provided custom `ignore` option, it would be breaking change: Added via a lightweight polyfill with pathe~~
- ~~Default ignores `["**/node_modules/**", "**/.git/**"]` added using simply regex matcher~~
> refactor: upgrade to  chokidar to v4

- docs/2.drivers/redis.md
This change mainly corrects the spelling of "hashtags" and adds links to the redis docs. (They also use "hash tags" sometimes though, so I'm not sure which is best.) 
But I think it might also be helpful to add a bit of nuance to this section. Forcing every item to the same slot will avoid the CROSSSLOT error, but isn't generally recommended. My assumption is a strategy similar to the one shown in the redis docs (slotting based on the user ID) would also work with unstorage, but there may be limitations such as `getKeys` not working. 
What are your thoughts here? (I can split this into a separate issue if it helps)
> docs(redis): update hashtags note

- src/drivers/deno-kv.ts
Use `normalizeKey` in `"../utils"` will cause problems. Check the built artifacts:
Before (BUG):
```js
// drivers/deno-kv.mjs
import { normalizeKey } from "../utils";
import { defineDriver, createError } from "./utils/index.mjs";
...
```
After:
```js
// drivers/deno-kv.mjs
import { defineDriver, createError, normalizeKey } from "./utils/index.mjs";
...
```
> fix(deno): avoid crossing package boundary in deno-kv driver

- docs/2.drivers/redis.md
- docs/2.drivers/upstash.md
- docs/2.drivers/vercel.md
- src/drivers/redis.ts
- src/drivers/upstash.ts
- src/drivers/vercel-kv.ts
resolves #418
These changes follow official Redis recommendations for production environments and improve handling of large datasets.
- Replaced blocking del with non-blocking unlink for better performance
- Implemented cursor-based scan instead of keys to prevent server blocking
> feat(redis, vercel-kv, upstash): use non-blocking methods

- src/drivers/session-storage.ts
I'm working on a custom implementation that falls back to a list of drivers when the main driver are not supported. For example, localStorage might be unavailable or unreliable in some mobile devices, so sessionStorage is a second option.
I need to log the name of the driver being supported, but I noticed that  the name of the `session-storage` is replaced by `localstorage` name:
This PR defines correctly the driver name of session-storage.
> fix(session-storage): correct `name`

- docs/2.drivers/azure.md
- src/drivers/azure-storage-blob.ts
- test/drivers/azure-storage-blob.test.ts
This PR adds raw item get/set support, similar to abandoned #442, but also adds test for that new procedures.
Also I have noticed that the current `removeItem` test fails, as `delete` operation with non-existent keys leads to an error. I _assume_ the intention is not to fail in such cases, so I have not changed the `removeItem` test, but added a check before attempting to delete the blob at the Azure Blob driver.
> feat(azure-storage-blob): add raw support

- src/drivers/s3.ts
Some S3 compatible providers (Supabase for ex.) return 200 instead of 204 on object delete. 
This shouldn't trigger an error as 200 indicates a success as well.
> fix(s3): accept `200` for delete response for better compatibility

- docs/2.drivers/database.md
I've changed variable `table` to `tableName` because the first one don't exist.
> docs(database): correct `tableName` config key

- docs/2.drivers/database.md
Oopsie, I forgot to change `table` to `tableName` in options, sorry. (#652)
> docs(database): correct tableName config key (2)

- src/drivers/vercel-blob.ts
The Vercel Blob driver was missing the options
> fix(vercel-blob): expose driver `options` 

- docs/2.drivers/redis.md
A couple small tweaks to the redis docs:
* Update the cluster warning to make it clear that the issue occurs when keys used within a single command are assigned to different hashslots. (Follow-up from https://github.com/unjs/unstorage/pull/593)
* Update the Github URL since the project is now in the redis org. (It was redirecting already but it doesn't hurt to have the new URL)
> docs(redis): update github links and cluster warning
